// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SiteEmprego.Models;
using System;

namespace SiteEmprego.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20170910015733_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiteEmprego.Models.Candidatura", b =>
                {
                    b.Property<long>("Idcandidatura")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CandidaturaAtiva");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<long?>("UsuarioIdUsuario");

                    b.Property<long?>("VagaIdVaga");

                    b.HasKey("Idcandidatura");

                    b.HasIndex("UsuarioIdUsuario");

                    b.HasIndex("VagaIdVaga");

                    b.ToTable("Candidatura");
                });

            modelBuilder.Entity("SiteEmprego.Models.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Email");

                    b.Property<string>("Estado");

                    b.Property<string>("Nome");

                    b.Property<string>("Password");

                    b.Property<bool>("UsuarioAtivo");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SiteEmprego.Models.Vaga", b =>
                {
                    b.Property<long>("IdVaga")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Descricao");

                    b.Property<string>("Estado");

                    b.Property<float>("Salario");

                    b.Property<string>("Titulo");

                    b.Property<long?>("UsuarioIdUsuario");

                    b.Property<bool>("VagaAtiva");

                    b.HasKey("IdVaga");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Vaga");
                });

            modelBuilder.Entity("SiteEmprego.Models.Candidatura", b =>
                {
                    b.HasOne("SiteEmprego.Models.Usuario", "Usuario")
                        .WithMany("Candidaturas")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.HasOne("SiteEmprego.Models.Vaga", "Vaga")
                        .WithMany("Candidaturas")
                        .HasForeignKey("VagaIdVaga");
                });

            modelBuilder.Entity("SiteEmprego.Models.Vaga", b =>
                {
                    b.HasOne("SiteEmprego.Models.Usuario", "Usuario")
                        .WithMany("Vagas")
                        .HasForeignKey("UsuarioIdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
